### ISSUE TITLE
Use gcode with function in .h file

### ISSUE THREAD

**Issue by lelibreauquotidien** [tinkersprojects/G-Code-Arduino-Library#10]
Good morning.
I would like to use the library with a function declared in an h-file.
My code is:
```
#include "core/functions.h"
#include <gcode.h>
void return_endstops_status();
commandscallback commands[1] = {{"L1",return_endstops_status}};
gcode Commands(1,commands);
```
My error is:
`undefined reference to return_endstops_status()`
Thank you

**Comment by tinkersprojects** [comment]
hey, i just tried it and you can do it, just need to make sure it is a void and not in a class. could you post more code please or send it to me on my email tinkersprojects@gmail.com. makes it a bit easier to work out the bug.

**Comment by lelibreauquotidien** [comment]
Send !
