### ISSUE TITLE
Function moviment() is a member of a class

### ISSUE THREAD

**Issue by ProtopIazma** [tinkersprojects/G-Code-Arduino-Library#11]
Hi.
How do I write code correctly if the function moviment() is a member of a class? For example in this case:
**class Moving
{
  public:
    void gotoLocation(double f,double x,double y,double z,double e);
    void moviment();
} ArmMoving;
commandscallback commands[1] = {"G0",ArmMoving.moviment};
gcode Commands(1,commands);**

The compiler writes the following error:
**cannot convert 'Moving::moviment' from type 'void (Moving::)()' to type 'CallbackFunction {aka void (*)()}'**

**Comment by tinkersprojects** [comment]
i'm looking into it but for the time being, you can just use a void function with the class function in it.
`
class Moving
{
public:
void gotoLocation(double f,double x,double y,double z,double e);
void moviment();
} ArmMoving;

void moviment()
{
ArmMoving.moviment
}

commandscallback commands[1] = {"G0",moviment};
gcode Commands(1,commands);
`
its a bit annoying but it will work until the other is worked out.

**Comment by ProtopIazma** [comment]
Thank. I would be thankful. I tried to pass this function through the pointer, but then the compiler writes an error about type mismatch.

**Comment by ProtopIazma** [comment]
Sorry, but the compiler for such a line:
**ArmMoving.moviment;**
Produces such an error: 
**invalid use of non-static member function 'void Moving::moviment()'**
