### ISSUE TITLE
Delta

### ISSUE THREAD

**Issue by Skywalkerf34** [tinkersprojects/G-Code-Arduino-Library#12]
Hi William,

I find your webpage and think you already did a great job, congrats!
I am trying to develop a Delta robot using some UBTECH smart serial servo, I Digg a lot to found how to use those as they don't provide any documentation nor support but now it works!
I design the hardware with 3D printed part.
Now I would like to control the robot with some Gcode like I can for my 3D printer or my CNC.
From what I understand you already do this with this Gcode lib and Your delta lib. would you be kind to put an example for that?

Kind regards

**Comment by tinkersprojects** [comment]
hey mate,
yea i can, it just may take some time. I'm a bit busy currently
feel free to contact me on discord: https://discord.gg/5PvYNj

Sincerely
William Bailes
https://tinkersprojects.com/
